# -*- coding: utf-8 -*-
"""Updated AI + Algorithm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-vo6bp45gvSiBhz3jk1jtS1ChBthfOpm
"""

import pandas as pd
import numpy as np
import random
import re

from google.colab import drive
drive.mount('/content/drive')

# Define the path to your main XLSX file.
XLSX_PATH = "/content/drive/MyDrive/CIC Algorithm/user_db_V2.xlsx"
OUTPUT_DIR = "/content/drive/MyDrive/CIC Algorithm/Schedule_Results"

# Maximum number of sections per faculty
MAX_LOAD = 3
# 假設 FLEXIBLE_MAX_LOAD_CAP 已經定義，例如 5
FLEXIBLE_MAX_LOAD_CAP = 5

"""# Load data"""

# --- Sheet Names to DataFrame Variable Mapping ---
# Dictionary mapping desired DataFrame variable names to the sheet names in the Excel file.
SHEET_MAP = {
    "semester_df": "CIC_Semester",
    "course_df": "CIC_Course",
    "offer_df": "CIC_CourseOffering",
    "faculty_df": "CIC_FacultyProfile",
    "preference_df": "CIC_FacultyPreference",
}

# Dictionary to hold the loaded DataFrames
dataframes = {}

print(f"--- Starting to read data from: {XLSX_PATH} ---")

# Load each required sheet into a separate DataFrame
for df_var_name, sheet_name in SHEET_MAP.items():
    try:
        # Read the Excel file using the specified sheet name
        df = pd.read_excel(XLSX_PATH, sheet_name=sheet_name)

        dataframes[df_var_name] = df
        print(f"✅ Successfully loaded '{sheet_name}' into DataFrame: {df_var_name} (Shape: {df.shape})")

    except Exception as e:
        print(f"❌ ERROR loading sheet '{sheet_name}': {e}")

# Assign DataFrames to the specific variables requested
semester_df = dataframes.get("semester_df")
course_df = dataframes.get("course_df")
offer_df = dataframes.get("offer_df")
faculty_df = dataframes.get("faculty_df")
preference_df = dataframes.get("preference_df")

"""# Load data from MySQL (need debug)"""

!pip install sqlalchemy pymysql

from sqlalchemy import create_engine
import pymysql

# ----------------------------------------------------
# 步驟 1: 配置 MySQL 連線資訊
# ----------------------------------------------------
# 請替換成您 MySQL Workbench 中使用的連線細節
DB_CONFIG = {
    'host': 'localhost', # 範例: 'localhost' 或 '127.0.0.1'
    'port': 3306,                     # 範例: 3306 (預設端口)
    'user': 'root',
    'password': '123456',
    'database': 'user_management',
}

# ----------------------------------------------------
# 步驟 2: 建立資料庫連線 Engine
# ----------------------------------------------------
# 構建資料庫連線 URL: 'mysql+pymysql://user:password@host:port/database'
DATABASE_URL = (
    f"mysql+pymysql://{DB_CONFIG['user']}:"
    f"{DB_CONFIG['password']}@"
    f"{DB_CONFIG['host']}:"
    f"{DB_CONFIG['port']}/"
    f"{DB_CONFIG['database']}"
)

# 創建 SQLAlchemy Engine
try:
    engine = create_engine(DATABASE_URL)
    print("✅ MySQL 資料庫連線 Engine 建立成功。")
except Exception as e:
    print(f"❌ 資料庫連線 Engine 建立失敗: {e}")
    raise

# ----------------------------------------------------
# 步驟 3: 定義表格名稱並載入 DataFrames
# ----------------------------------------------------
# 根據您在 Excel 中的工作表名稱，假設 MySQL 資料庫中的表格名稱與之相同。
TABLE_NAMES_MAP = {
    "semester_df": "CIC_Semester",
    "course_df": "CIC_Course",
    "offer_df": "CIC_CourseOffering",
    "faculty_df": "CIC_FacultyProfile",
    "preference_df": "CIC_FacultyPreference",
}

# 儲存載入的 DataFrames
dataframes = {}

print("\n--- 開始從 MySQL 載入 DataFrames ---")

for df_var_name, table_name in TABLE_NAMES_MAP.items():
    try:
        # 使用 pd.read_sql_query 執行 SELECT * 查詢，並直接載入為 DataFrame
        sql_query = f"SELECT * FROM {table_name};"
        df = pd.read_sql_query(sql_query, engine)

        # 將 DataFrame 存入 dataframes 字典中，使用您期望的變數名作為 key
        dataframes[df_var_name] = df
        print(f"✅ 成功載入表格 '{table_name}' 到 '{df_var_name}' (Shape: {df.shape})")

    except Exception as e:
        print(f"❌ ERROR 載入表格 '{table_name}' 失敗: {e}")
        # 如果載入失敗，應停止並拋出錯誤
        raise

# ----------------------------------------------------
# 步驟 4: 賦值給您的最終變數
# ----------------------------------------------------

semester_df = dataframes.get("semester_df")
course_df = dataframes.get("course_df")
offer_df = dataframes.get("offer_df")
faculty_df = dataframes.get("faculty_df")
preference_df = dataframes.get("preference_df")

print("\n🎉 所有 DataFrames 成功從 MySQL 載入並賦值完成！")

# ----------------------------------------------------
# 步驟 5: 關閉 Engine 連線
# ----------------------------------------------------
engine.dispose()

"""# Prepare data"""

# --- 1. Optimized Data Preparation: Expand, Merge Category, and Sort ---
print("--- 1. Optimized Data Preparation ---")

# 1.1: Determine Active Semester
try:
    ACTIVE_SEMESTER_ID = semester_df[semester_df['semesterIsActive'] == 'T']['semesterId'].iloc[0]
except IndexError: # Use IndexError as iloc[0] raises this when no rows match
    print("ERROR: Could not find active semester.")

# 1.2: Expand Sections
active_offerings_df = offer_df[offer_df['semesterId'] == ACTIVE_SEMESTER_ID].copy()
list_of_dfs = []
for _, row in active_offerings_df.iterrows():
    n = int(row['sectionQuantity'])
    temp_df = pd.DataFrame([row] * n)
    section_numbers = range(1, n + 1)
    temp_df['sectionId'] = [f"S{i}" for i in section_numbers]
    temp_df['total_sections'] = temp_df['sectionQuantity']
    list_of_dfs.append(temp_df)

df_sections_to_assign = pd.concat(list_of_dfs, ignore_index=True)
df_sections_to_assign = df_sections_to_assign[['offeringId', 'courseId', 'semesterId', 'sectionId', 'total_sections']]

# 1.3: Merge courseCategory
course_category_map = course_df[['courseId', 'courseCategory']]
df_sections_to_assign = pd.merge(
    df_sections_to_assign,
    course_category_map,
    on='courseId',
    how='left'
)

# Initialize assignment column
df_sections_to_assign['assignedFacultyId'] = 'NOT_ASSIGNED'

# 1.4: Define Priority Sorting (Core before Elective, Large Courses first)
# Create a numerical column for sorting: Core=0, Elective=1 (Core comes first)
df_sections_to_assign['category_rank'] = df_sections_to_assign['courseCategory'].apply(
    lambda x: 0 if x == 'Core' else 1
)

# Final Sorting: Category (ASC) -> Total Sections (DESC) -> Offering ID (ASC for stability)
df_sections_to_assign = df_sections_to_assign.sort_values(
    by=['category_rank', 'total_sections', 'offeringId'],
    ascending=[True, False, True],
    kind='mergesort' # Maintain stability for tie-breaking
).reset_index(drop=True)

print(f"✅ Final sections DataFrame prepared and sorted for assignment: {len(df_sections_to_assign)} sections.")
print("Sections are prioritized: Core (large first) -> Elective (large first).")

# display all rows of df_sections_to_assign
pd.set_option('display.max_rows', None)
df_sections_to_assign

"""# Calculate faculty indicator"""

# --- 2. Indicator Calculation (df_faculty_indicator) ---
print("--- 2. Indicator Calculation ---")
courses_to_assign = df_sections_to_assign['courseId'].unique()
indicator_df = preference_df[
    (preference_df['semesterId'] == ACTIVE_SEMESTER_ID) &
    (preference_df['courseId'].isin(courses_to_assign))
].copy()
faculty_exp_df = faculty_df[['facultyUserId', 'facultyExperience']].copy()

# Preference Score
max_rank = indicator_df['priorityRank'].max() if not indicator_df.empty else 5
indicator_df['preference_score'] = (max_rank + 1) - indicator_df['priorityRank']

# Experience Score
indicator_df = pd.merge(indicator_df, faculty_exp_df, on='facultyUserId', how='left')
def calculate_experience_score(row):
    course_id = row['courseId']
    experience_str = str(row['facultyExperience'])
    if pd.isna(experience_str) or experience_str == 'NULL':
        return 0
    pattern = r'\b' + re.escape(course_id) + r'\b'
    return 5 if re.search(pattern, experience_str) else 0
indicator_df['experience_score'] = indicator_df.apply(calculate_experience_score, axis=1)

# Final Indicator
WEIGHT_PREFERENCE = 0.4
WEIGHT_EXPERIENCE = 0.6
indicator_df['final_indicator'] = (indicator_df['preference_score'] * WEIGHT_PREFERENCE) + (indicator_df['experience_score'] * WEIGHT_EXPERIENCE)

# Add all course/faculty combinations for unassigned cases (score 0)
all_possible_assignments = pd.DataFrame({'courseId': courses_to_assign}).merge(
    faculty_df[['facultyUserId']], how='cross'
)
df_faculty_indicator = all_possible_assignments.merge(
    indicator_df[['facultyUserId', 'courseId', 'preference_score', 'experience_score', 'final_indicator']],
    on=['facultyUserId', 'courseId'],
    how='left'
).fillna({
    'preference_score': 0,
    'experience_score': 0,
    'final_indicator': 0
})
df_faculty_indicator = df_faculty_indicator.sort_values(
    by=['final_indicator', 'facultyUserId'],
    ascending=[False, True]
).reset_index(drop=True)

print(f"Indicator calculated for {len(df_faculty_indicator)} faculty-course pairs.")

df_faculty_indicator

"""# Define functions

## def get_best_candidate_df
"""

# --- 1. 輔助函式 (Common Base Function) ---

def get_best_candidate_df(course_id, df_indicator):
    """
    【共同基礎步驟】篩選教師對指定課程的適配性指標，並添加隨機欄位進行同分亂序。

    Args:
        course_id (str): 課程 ID (e.g., 'CIC6173').
        df_indicator (pd.DataFrame): 包含 final_indicator 等指標的教師-課程適配表。

    Returns:
        pd.DataFrame: 候選人列表，已按 final_indicator (高到低) 和 random_sort (高到低) 排序。
    """
    # 1. 篩選出所有針對此課程的教師候選人
    candidates_df = df_indicator[df_indicator['courseId'] == course_id].copy()

    # 2. 加入隨機欄位，用於同分時的隨機分配（亂序/Tie-breaking）
    # 確保每次呼叫此函式時，隨機數都會重新產生，實現真正的隨機分配。
    # Set random seed = 37
    # candidates_df['random_sort'] = np.random.rand(len(candidates_df))
    candidates_df['random_sort'] = np.random.default_rng(seed=37).random(len(candidates_df))

    # 3. 排序：第一優先 Final Indicator (DESC)，第二優先 Random Sort (DESC)
    candidates_df = candidates_df.sort_values(
        by=['final_indicator', 'random_sort'],
        ascending=[False, False]
    ).reset_index(drop=True)

    return candidates_df

"""## def run_assignment"""

def run_assignment(df_sections_in, df_indicator_in, initial_max_load, method_type):
    """執行分配，Method 1: 嚴格 Max Load, 嚴格 Preference > 0。"""

    # 使用複本以確保原始數據不被修改
    df_sections = df_sections_in.copy()
    df_indicator = df_indicator_in.copy()

    unique_faculty = df_indicator['facultyUserId'].unique()
    faculty_load = {uid: 0 for uid in unique_faculty}
    current_max_load = initial_max_load

    sections_to_process = df_sections[df_sections['assignedFacultyId'] == 'NOT_ASSIGNED'].index

    for i in sections_to_process:
        section = df_sections.loc[i]
        course_id = section['courseId']

        candidates_df = get_best_candidate_df(course_id, df_indicator)
        assignedFacultyId = 'NOT_ASSIGNED'

        for _, candidate in candidates_df.iterrows():
            candidate_id = candidate['facultyUserId']
            pref_score = candidate['preference_score']

            # 約束檢查 1：Max Load (嚴格 < MAX_LOAD)
            if faculty_load[candidate_id] >= current_max_load:
                continue

            # 約束檢查 2：Method 1 (Preference Score 限制: 必須大於 0)
            if method_type == 1 and pref_score == 0:
                continue

            # 找到最優且符合約束的教師
            assignedFacultyId = candidate_id
            break # 找到第一個符合條件的就分配

        # 執行分配動作
        if assignedFacultyId != 'NOT_ASSIGNED':
            df_sections.loc[i, 'assignedFacultyId'] = assignedFacultyId
            # faculty_load['sections_assigned'] add 1 after assigned to the faculty_load[assignedFacultyId]
            faculty_load[assignedFacultyId] += 1

    # 最終結果彙整
    total_sections = len(df_sections)
    total_assigned = len(df_sections[df_sections['assignedFacultyId'] != 'NOT_ASSIGNED'])
    print(f"Total Sections: {total_sections}, Total Assigned: {total_assigned}")
    load_df = pd.Series(faculty_load).to_frame(name='sections_assigned').reset_index().rename(columns={'index': 'facultyUserId'})

    return {
        'assignment_df': df_sections,
        'load_summary': load_df,
        'total_sections': total_sections,
        'total_assigned': total_assigned,
        'method_max_load': load_df['sections_assigned'].max()
    }

"""## def run_assignment_flexible_maxload"""

def run_assignment_flexible_maxload(df_sections_in, df_indicator_in, initial_max_load, method_type, max_load_cap=5):
    """
    執行彈性負載分配 (Method 3 & 4)。
    - Method 3 (Type 3): 優先保證所有 Core 課程完成分配，隨即停止。
    - Method 4 (Type 4): 優先保證所有課程 (Core + Elective) 完成分配，隨即停止。

    :param initial_max_load: 初始最大負載。
    :param method_type: 必須是 3 或 4。
    :param max_load_cap: 負載的絕對上限。
    """

    if method_type not in [3, 4]:
        raise ValueError("Method Type for flexible load must be 3 or 4.")

    # 使用複本以確保原始數據不被修改
    df_sections = df_sections_in.copy()

    # 初始化負載字典 (確保 Key 類型一致性)
    unique_faculty = df_indicator_in['facultyUserId'].unique()
    faculty_load = {str(uid): 0 for uid in unique_faculty}

    # 設置初始負載：讓第一次進入 while 迴圈時，負載從 initial_max_load 開始
    current_max_load = initial_max_load - 1

    print(f"--- 執行 Method {method_type}: 彈性負載 ({initial_max_load} -> {max_load_cap}) ---")

    # 核心迭代循環
    while current_max_load < max_load_cap:

        # 1. 提高負載限制
        current_max_load += 1
        print(f"  > 啟動分配階段：Max Load = {current_max_load}")

        # 2. 檢查當前所有未分配的 Sections
        unassigned_sections = df_sections[df_sections['assignedFacultyId'] == 'NOT_ASSIGNED']

        # 終止條件 A (Method 4/總目標達成): 所有課程分配完畢
        if unassigned_sections.empty:
            print(f"  ✅ 階段 {current_max_load}: 所有課程已分配完畢 (總目標達成)。")
            break

        # 終止條件 B (Method 3 目標達成): 所有 Core 課程分配完畢
        unassigned_core = unassigned_sections[unassigned_sections['courseCategory'] == 'Core']
        unassigned_core_count = len(unassigned_core)

        if method_type == 3 and unassigned_core_count == 0:
            print(f"  ✅ 階段 {current_max_load}: 核心課程已全部分配完畢 (Method 3 目標達成)。")
            # Method 3 達成目標後，立即跳出整個 while 迴圈
            break

        assigned_in_phase = 0

        # 3. 確定本階段要嘗試分配的 Sections 列表 (關鍵修正)
        if method_type == 3:
            # Method 3: 只分配 Core 課程 (因為 Elective 課程在 Method 3 中被視為非必需分配)
            sections_to_assign_in_phase = unassigned_core
        else: # method_type == 4
            # Method 4: 分配所有未分配的課程 (Core + Elective)
            sections_to_assign_in_phase = unassigned_sections

        sections_to_process_index = sections_to_assign_in_phase.index

        # 4. 對列表中的 Sections 進行分配嘗試
        for i in sections_to_process_index:
            section = df_sections.loc[i]
            course_id = section['courseId']

            candidates_df = get_best_candidate_df(course_id, df_indicator_in)
            assignedFacultyId = 'NOT_ASSIGNED'

            for _, candidate in candidates_df.iterrows():
                candidate_id = str(candidate['facultyUserId'])

                # 約束檢查 1：Max Load (嚴格 < current_max_load)
                if faculty_load.get(candidate_id, 0) >= current_max_load:
                    continue

                # Method 3/4: 無 Preference Score 限制

                # 找到最優且符合約束的教師
                assignedFacultyId = candidate_id
                break

            # 執行分配動作
            if assignedFacultyId != 'NOT_ASSIGNED':
                df_sections.loc[i, 'assignedFacultyId'] = assignedFacultyId
                faculty_load[assignedFacultyId] = faculty_load.get(assignedFacultyId, 0) + 1
                assigned_in_phase += 1

        # 輸出進度
        unassigned_total_after_phase = len(df_sections[df_sections['assignedFacultyId'] == 'NOT_ASSIGNED'])
        print(f"  > 本輪分配了 {assigned_in_phase} 節課程。剩餘未分配總數: {unassigned_total_after_phase}")


    # 最終結果彙整
    total_sections = len(df_sections_in)
    total_assigned = len(df_sections[df_sections['assignedFacultyId'] != 'NOT_ASSIGNED'])

    # 彙整負載
    load_df = pd.Series(faculty_load).to_frame(name='sections_assigned').reset_index().rename(columns={'index': 'facultyUserId'})

    if current_max_load == max_load_cap and not df_sections[df_sections['assignedFacultyId'] == 'NOT_ASSIGNED'].empty:
        print(f"  🚫 警告：已達到負載上限 {max_load_cap}，仍有課程未分配。")

    return {
        'assignment_df': df_sections,
        'load_summary': load_df,
        'total_sections': total_sections,
        'total_assigned': total_assigned,
        'method_max_load': load_df['sections_assigned'].max()
    }

"""# Assign faculties with 4 different conditions"""

def process_and_print_results(method_name, result, preference_df, initial_max_load):
    # ... (代碼與您之前提供的相同，用於創建 df_output, 合併 preferenceRank) ...

    # 複製分配結果 DataFrame
    df_output = result['assignment_df'].copy()

    # 確保 df_output 具有指定的欄位順序 (並移除不必要的 'category_rank' 欄位)
    columns_to_keep = ['offeringId', 'courseId', 'semesterId', 'sectionId', 'total_sections', 'courseCategory', 'assignedFacultyId']
    if 'category_rank' in df_output.columns:
        df_output.drop(columns=['category_rank'], inplace=True, errors='ignore')

    df_output = df_output[columns_to_keep]

    # 確保 'assignedFacultyId' 是字串以便合併
    df_output['assignedFacultyId'] = df_output['assignedFacultyId'].astype(str)

    # 數據合併：加入 priorityRank
    df_output = pd.merge(
        df_output,
        preference_df[['facultyUserId', 'courseId', 'priorityRank']].astype({'facultyUserId': str}),
        left_on=['assignedFacultyId', 'courseId'],
        right_on=['facultyUserId', 'courseId'],
        how='left'
    )

    # ----------------------------------------------------
    # 關鍵修正: 確保 preference_df 中 'priorityRank' 的最大值
    # ----------------------------------------------------
    max_rank = preference_df['priorityRank'].max()
    # 將 Penalty Rank 定義為比最大 Rank 多 1
    PENALTY_RANK = max_rank + 1 if pd.notna(max_rank) else 5 # 假設預設 Max Rank = 4, Penalty = 5

    # 清理和整理
    df_output.drop(columns=['facultyUserId'], inplace=True, errors='ignore')

    # 這裡不再將 NaN 填 0，而是將其標記為 NaN，留給後續計算處理
    df_output['priorityRank'] = df_output['priorityRank'].astype(int, errors='ignore')


    # ----------------------------------------------------
    # 計算新的 KPI 指標
    # ----------------------------------------------------

    total_sections = len(df_output)
    total_assigned = result['total_assigned']

    # 篩選已分配的 Sections
    assigned_df = df_output[df_output['assignedFacultyId'] != 'NOT_ASSIGNED'].copy()
    assigned_count = len(assigned_df)

    # 計算 Core/Elective 的分配數量 (用於 assigned rate)
    assigned_core = len(assigned_df[assigned_df['courseCategory'] == 'Core'])
    assigned_elective = len(assigned_df[assigned_df['courseCategory'] == 'Elective'])


    # --- KPI 1: 偏好課程的平均 Rank (Avg Pref Rank) ---
    # 僅限於那些教師明確表達了偏好 (PriorityRank > 0) 的分配
    assigned_with_pref = assigned_df[assigned_df['priorityRank'] > 0]
    assigned_with_pref_count = len(assigned_with_pref)

    avg_pref_rank = assigned_with_pref['priorityRank'].mean() if assigned_with_pref_count > 0 else 0

    # --- KPI 2: 所有分配的滿意度分數 (Overall Satisfaction Score) ---
    # 給予沒有偏好的分配 (NaNs/0s) 懲罰分數 PENALTY_RANK
    # 注意：由於您在初始代碼中將未分配課程的 assignedFacultyId 設為 NOT_ASSIGNED，
    # 這裡的 assigned_df['priorityRank'] 應該是 NaN 或 > 0 的整數。

    # 計算加權分數：將 NaN 視為懲罰分數
    assigned_df['SatisfactionRank'] = assigned_df['priorityRank'].fillna(PENALTY_RANK).astype(int)

    overall_satisfaction_score = assigned_df['SatisfactionRank'].mean() if assigned_count > 0 else 0


    # --- KPI 3: 無偏好分配率 (No Preference Rate) ---
    # 統計那些被分配但 PriorityRank 為 NaN 的課程
    no_pref_assigned_count = assigned_df['priorityRank'].isna().sum()
    no_preference_rate = no_pref_assigned_count / assigned_count if assigned_count > 0 else 0

    # ----------------------------------------------------
    # 剩餘的 KPI 計算和輸出部分 (與之前相同或輕微調整)
    # ----------------------------------------------------

    total_unassigned = total_sections - total_assigned
    max_load_achieved = result['method_max_load']
    total_assigned_rate = total_assigned / total_sections if total_sections > 0 else 0

    total_core = len(df_output[df_output['courseCategory'] == 'Core'])
    core_assigned_rate = assigned_core / total_core if total_core > 0 else 0

    total_elective = len(df_output[df_output['courseCategory'] == 'Elective'])
    elective_assigned_rate = assigned_elective / total_elective if total_elective > 0 else 0

    load_summary = result['load_summary']
    load_std_dev = load_summary['sections_assigned'].std() if len(load_summary) > 1 else 0

    # 輸出摘要資訊 (使用新的欄位)
    print(f"\n--- {method_name} 執行摘要 ---")
    print(f"* 總 Sections 數量: **{total_sections}**")
    print(f"* 成功分配數量: **{total_assigned}** ({total_assigned_rate:.1%})")
    print(f"* 未分配數量: **{total_unassigned}**")
    print(f"* 初始最大負載 (Max Load): **{initial_max_load}**")
    print(f"* 實際最大教師負載: **{max_load_achieved}**")
    print(f"* **Core Assigned Rate:** **{core_assigned_rate:.1%}**")
    print(f"* **Elective Assigned Rate:** **{elective_assigned_rate:.1%}**")
    print(f"* **平均 Preference Rank (Pref > 0):** **{avg_pref_rank:.2f}** (僅計入有偏好課程)")
    print(f"* **總體滿意度分數 (Penalty={PENALTY_RANK}):** **{overall_satisfaction_score:.2f}** (越低越好)")
    print(f"* **Load Std Dev:** **{load_std_dev:.2f}** (越低越好)")


    print(f"\n--- {method_name} (結果範例, 前 5 筆) ---")
    print(df_output[['offeringId', 'courseId', 'courseCategory', 'assignedFacultyId', 'priorityRank']].head().to_markdown(index=False))

    print(f"\n--- {method_name} 教師負載分佈 (Load Summary) ---")
    load_summary_sorted = load_summary.sort_values(by='sections_assigned', ascending=False)
    print(load_summary_sorted.to_markdown(index=False))

    # 檢查未分配的 Section
    unassigned_sections = df_output[df_output['assignedFacultyId'] == 'NOT_ASSIGNED']
    print(f"\n未分配的 Section 列表數量: **{len(unassigned_sections)}**")

    # 建立單一結果字典，供後續彙總使用
    kpi_dict = {
        'Method': method_name,
        'Total Assigned Rate': total_assigned_rate,
        'Core Assigned Rate': core_assigned_rate,
        'Elective Assigned Rate': elective_assigned_rate,
        'Avg Pref Rank': avg_pref_rank,                 # 新的：僅計算 > 0 的 Rank
        'Overall Satisfaction Score': overall_satisfaction_score, # 新的：帶懲罰分數
        'No Preference Rate': no_preference_rate,
        'Max Load Achieved': max_load_achieved,
        'Load Std Dev': load_std_dev,
        'Total Sections': total_sections,
        'Total Assigned': total_assigned
    }

    return df_output, load_summary_sorted, unassigned_sections, kpi_dict

def create_kpi_summary_df(kpi_results_list):
    """
    將所有 Method 的 KPI 字典彙總成一個 DataFrame 以便比較。
    """
    kpi_df = pd.DataFrame(kpi_results_list)

    # 重新排列欄位順序以提高可讀性
    kpi_df = kpi_df[[
        'Method',
        'Total Assigned Rate',
        'Core Assigned Rate',
        'Elective Assigned Rate',
        'Max Load Achieved',
        'Load Std Dev',
        'Avg Pref Rank',                    # 修正：新欄位
        'Overall Satisfaction Score',       # 修正：新欄位
        'No Preference Rate',
        'Total Sections',
        'Total Assigned'
    ]]

    # 格式化百分比和分數
    kpi_df['Total Assigned Rate'] = (kpi_df['Total Assigned Rate'] * 100).round(1).astype(str) + '%'
    kpi_df['Core Assigned Rate'] = (kpi_df['Core Assigned Rate'] * 100).round(1).astype(str) + '%'
    kpi_df['Elective Assigned Rate'] = (kpi_df['Elective Assigned Rate'] * 100).round(1).astype(str) + '%'

    kpi_df['Avg Pref Rank'] = kpi_df['Avg Pref Rank'].round(2)
    kpi_df['Overall Satisfaction Score'] = kpi_df['Overall Satisfaction Score'].round(2)

    kpi_df['No Preference Rate'] = (kpi_df['No Preference Rate'] * 100).round(1).astype(str) + '%'
    kpi_df['Load Std Dev'] = kpi_df['Load Std Dev'].round(2)

    return kpi_df

# ----------------------------------------------------
# 3. 運行所有 Method 的簡潔代碼 (最終版本)
# ----------------------------------------------------

# 假設所有輸入變數已定義: MAX_LOAD, FLEXIBLE_MAX_LOAD_CAP,
# df_sections_to_assign, df_faculty_indicator, preference_df, run_assignment, run_assignment_flexible_maxload

kpi_results = []

# --- Method 1 ---
result_m1 = run_assignment(df_sections_to_assign, df_faculty_indicator, MAX_LOAD, 1)
df_output1, load_summary_m1, unassigned_sections_m1, kpi_m1 = process_and_print_results(
    "Method 1 (Strict, Pref > 0)", result_m1, preference_df, MAX_LOAD
)
kpi_results.append(kpi_m1)

# --- Method 2 ---
result_m2 = run_assignment(df_sections_to_assign, df_faculty_indicator, MAX_LOAD, 2)
df_output2, load_summary_m2, unassigned_sections_m2, kpi_m2 = process_and_print_results(
    "Method 2 (Strict, No Pref)", result_m2, preference_df, MAX_LOAD
)
kpi_results.append(kpi_m2)

# --- Method 3 ---
result_m3 = run_assignment_flexible_maxload(df_sections_to_assign, df_faculty_indicator, MAX_LOAD, 3, max_load_cap=FLEXIBLE_MAX_LOAD_CAP)
df_output3, load_summary_m3, unassigned_sections_m3, kpi_m3 = process_and_print_results(
    "Method 3 (Flexible, Core Only)", result_m3, preference_df, MAX_LOAD
)
kpi_results.append(kpi_m3)

# --- Method 4 ---
result_m4 = run_assignment_flexible_maxload(df_sections_to_assign, df_faculty_indicator, MAX_LOAD, 4, max_load_cap=FLEXIBLE_MAX_LOAD_CAP)
df_output4, load_summary_m4, unassigned_sections_m4, kpi_m4 = process_and_print_results(
    "Method 4 (Flexible, All Sections)", result_m4, preference_df, MAX_LOAD
)
kpi_results.append(kpi_m4)

# --- 最終 KPI 比較 ---
final_kpi_summary = create_kpi_summary_df(kpi_results)
print("🌟 **四種 Method 最終 KPI 彙總比較** 🌟")
# covert row and col of final_kpi_summary
final_kpi_summary = final_kpi_summary.T
final_kpi_summary.columns = final_kpi_summary.iloc[0]
final_kpi_summary = final_kpi_summary[1:]


final_kpi_summary

# 插入一段: 將4個outputs和final_kpi_summary輸出成excel，存在OUTPUT_DIR

pip install XlsxWriter

import os

# Define the output Excel file path
excel_output_path = os.path.join(OUTPUT_DIR, "Schedules.xlsx")
os.makedirs(OUTPUT_DIR, exist_ok=True)
# Create a Pandas Excel writer using XlsxWriter as the engine.
# The engine property is important for performance and compatibility.
with pd.ExcelWriter(excel_output_path, engine='xlsxwriter') as writer:
    # Write each DataFrame to a different worksheet.
    df_output1.to_excel(writer, sheet_name='Method 1 Results', index=False)
    load_summary_m1.to_excel(writer, sheet_name='Method 1 Load Summary', index=False)
    unassigned_sections_m1.to_excel(writer, sheet_name='Method 1 Unassigned', index=False)

    df_output2.to_excel(writer, sheet_name='Method 2 Results', index=False)
    load_summary_m2.to_excel(writer, sheet_name='Method 2 Load Summary', index=False)
    unassigned_sections_m2.to_excel(writer, sheet_name='Method 2 Unassigned', index=False)

    df_output3.to_excel(writer, sheet_name='Method 3 Results', index=False)
    load_summary_m3.to_excel(writer, sheet_name='Method 3 Load Summary', index=False)
    unassigned_sections_m3.to_excel(writer, sheet_name='Method 3 Unassigned', index=False)

    df_output4.to_excel(writer, sheet_name='Method 4 Results', index=False)
    load_summary_m4.to_excel(writer, sheet_name='Method 4 Load Summary', index=False)
    unassigned_sections_m4.to_excel(writer, sheet_name='Method 4 Unassigned', index=False)

    final_kpi_summary.to_excel(writer, sheet_name='KPI Summary', index=True)

print(f"✅ All assignment results and KPI summary saved to: {excel_output_path}")

"""# Gemini"""

# 步骤 1: 安装 Google GenAI SDK
!pip install google-genai pandas -q

# 导入必要的库
from google import genai
from google.colab import userdata
import pandas as pd
import os

# --- 注意事项 ---
# 强烈建议使用 Colab 的“Secret Manager”来安全存储您的 API Key。
# 1. 点击 Colab 左侧的“钥匙”图标 (Secret Manager)。
# 2. 创建一个新 Secret，名称为 GEMINI_API_KEY。
# 3. 将您的 Google AI Studio API Key 粘贴进去。
# -----------------

# 步骤 2: 初始化 Gemini 客户端
try:
    # 尝试从 Secret Manager 获取 API Key
    API_KEY = userdata.get('GEMINI_API_KEY')
    os.environ['GEMINI_API_KEY'] = API_KEY
    client = genai.Client()
    print("Gemini 客户端初始化成功！")
except Exception as e:
    print("❗ 警告：无法从 Colab Secret Manager 获取 GEMINI_API_KEY。")
    print("请确保您已在 Secret Manager 中设置好密钥。")
    print(f"错误信息: {e}")

def generate_ai_report(kpi_data: pd.DataFrame) -> str:
    """
    使用 Gemini 2.5 Flash 模型，根据 KPI 结果生成专业的英文分析报告。

    Args:
        kpi_data: 包含排课算法结果和 KPI 指标的 Pandas DataFrame。

    Returns:
        生成的英文分析报告文本。
    """
    # 将 DataFrame 转换为 Markdown 或更易读的文本格式，作为 Prompt 的输入
    kpi_text = kpi_data.to_markdown(index=False)

    # 定义系统提示词 (System Instruction)，确保模型扮演专业角色
    system_instruction = (
        "You are an expert academic scheduling analyst. "
        "Your task is to analyze four different faculty assignment methodologies and "
        "generate a concise, professional English report for the Academic Dean, "
        "strictly following the provided analysis requirements and report format."
    )

    # 定义用户提示词 (User Prompt)，包含数据和具体要求
    prompt_template = f"""
    The following table summarizes the Key Performance Indicators (KPIs) for four different assignment methods (Method 1 to Method 4). Note that lower rank scores (Avg Pref Rank, Overall Satisfaction Score) and lower Load Std Dev are generally better.

    **[DATA INPUT]**
    {kpi_text}

    **[ANALYSIS REQUIREMENTS]**
    1.  **Overall Assignment (Coverage):** Compare the Total, Core, and Elective Assigned Rates. Clearly state which method achieved the highest coverage, and highlight the difference between Method 3 (Core-focused) and Method 4 (All-focused).
    2.  **Quality of Assignment (Preference/Satisfaction):** Analyze 'Avg Pref Rank' (preference-only assignments) and 'Overall Satisfaction Score' (all assignments, including penalty for no-preference). Identify the method that best respects faculty preference. Discuss the trade-off between coverage and quality (e.g., does Method 4's high coverage come at the expense of preference quality?).
    3.  **Faculty Load and Equity:** Analyze 'Max Load Achieved' and 'Load Std Dev'. Recommend the method that provides the best balance of equity (low Std Dev) while maintaining efficiency.
    4.  **Conclusion & Recommendation:** Summarize the findings and provide a final recommendation for the most balanced and effective assignment strategy.

    **[REPORT FORMAT]**
    The report must be professional, use clear section headings (like 1. Coverage Analysis, 2. Quality Analysis, etc.), and be written entirely in English.
    """

    try:
        # 调用 Gemini API (使用最新的 flash 模型，性能优异)
        response = client.models.generate_content(
            model='gemini-2.5-flash',  # 推荐模型
            contents=prompt_template,
            config=genai.types.GenerateContentConfig(
                system_instruction=system_instruction,
                temperature=0.2 # 使用较低的温度，以获得更严谨、事实性的报告
            )
        )

        return response.text

    except Exception as e:
        print(f"❌ Gemini API 调用失败: {e}")
        return "Error: Could not generate AI report due to API failure."


print("--- 原始 KPI 数据 ---")
print(final_kpi_summary.to_markdown(index=False))
print("\n" + "="*50 + "\n")

# 生成报告
print("--- Gemini AI 生成报告 ---")
report = generate_ai_report(final_kpi_summary)
print(report)

report_output_path = os.path.join(OUTPUT_DIR, "AI_Analysis_Report.txt")

os.makedirs(OUTPUT_DIR, exist_ok=True)

with open(report_output_path, "w", encoding="utf-8") as f:
    f.write(report)

print(f"✅ AI analysis report saved to: {report_output_path}")